# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

module Seeds
  def topic_areas
   [{ id: 1, title: 'Demographics'  },
    { id: 2, title: 'Supply'        },
    { id: 3, title: 'Affordability' }]
  end

  def topics
   [{ id: 1, title: 'Population',                         topic_area_id: 1 },
    { id: 2, title: 'Population Projections',             topic_area_id: 1 },
    { id: 3, title: 'Households',                         topic_area_id: 1 },
    { id: 4, title: 'Household Projections',              topic_area_id: 1 },
    { id: 5, title: 'Stock',                              topic_area_id: 2 },
    { id: 6, title: 'Permits',                            topic_area_id: 2 },
    { id: 7, title: 'Cost Burden',                        topic_area_id: 3 },
    { id: 8, title: 'Subsidized Housing Inventory (SHI)', topic_area_id: 3 },
    { id: 9, title: 'Affordability Gap',                  topic_area_id: 3 }]
  end

  def subtopics
   [{ id: 1,  title: 'Year',             topic_id: 1 },
    { id: 2,  title: 'Age',              topic_id: 1 },
    { id: 3,  title: 'Race',             topic_id: 1 },
    { id: 4,  title: 'Year',             topic_id: 2 },
    { id: 5,  title: 'Age',              topic_id: 2 },
    { id: 6,  title: 'Type',             topic_id: 3 },
    { id: 7,  title: 'Tenure',           topic_id: 3 },
    { id: 8,  title: 'Year',             topic_id: 3 },
    { id: 9,  title: 'Age',              topic_id: 3 },
    { id: 10, title: 'Year',             topic_id: 4 },
    { id: 11, title: 'Age',              topic_id: 4 },
    { id: 12, title: 'Tenure',           topic_id: 4 },
    { id: 13, title: 'Type',             topic_id: 5 },
    { id: 14, title: 'Age',              topic_id: 5 },
    { id: 15, title: 'Tenure by Year',   topic_id: 6 },
    { id: 16, title: 'AMI',              topic_id: 7 },
    { id: 17, title: 'Income Limits',    topic_id: 7 },
    { id: 18, title: 'Severity',         topic_id: 7 },
    { id: 19, title: 'Household Type',   topic_id: 7 },
    { id: 20, title: 'Subsidized Units', topic_id: 8 },
    { id: 21, title: 'Income',           topic_id: 9 },
    { id: 22, title: 'AMI',              topic_id: 9 }]
  end

  def fields
    [{ id: 1,   title: 'pop_1990',   subtopic_id: 1,  alias: "Population in 1990"                                                                                       },
     { id: 2,   title: 'pop_2000',   subtopic_id: 1,  alias: "Population in 2000"                                                                                       },
     { id: 3,   title: 'pop_2010',   subtopic_id: 1,  alias: "Population in 2010"                                                                                       },
     { id: 4,   title: 'pop_20sr',   subtopic_id: 1,  alias: "Projected Population in 2020"                                                                             },
     { id: 5,   title: 'pop_30sr',   subtopic_id: 1,  alias: "Projected Population in 2030"                                                                             },
     { id: 6,   title: 'pop90_5_19', subtopic_id: 2,  alias: "Population for Ages 5-19 in 1990"                                                                         },
     { id: 7,   title: 'pop00_5_19', subtopic_id: 2,  alias: "Population for Ages 5-19 in 2000"                                                                         },
     { id: 8,   title: 'pop10_5_19', subtopic_id: 2,  alias: "Population for Ages 5-19 in 2010"                                                                         },
     { id: 9,   title: 'pop20_5_19', subtopic_id: 5,  alias: "Projected Population for Ages 5-19 in 2020"                                                               },
     { id: 10,  title: 'pop30_5_19', subtopic_id: 5,  alias: "Projected Population for Ages 5-19 in 2030"                                                               },
     { id: 11,  title: 'pop90_2034', subtopic_id: 2,  alias: "Population for Ages 20-34 in 1990"                                                                        },
     { id: 12,  title: 'pop00_2034', subtopic_id: 2,  alias: "Population for Ages 20-34 in 2000"                                                                        },
     { id: 13,  title: 'pop10_2034', subtopic_id: 2,  alias: "Population for Ages 20-34 in 2010"                                                                        },
     { id: 14,  title: 'pop20_2034', subtopic_id: 5,  alias: "Projected Population for Ages 20-34 in 2020"                                                              },
     { id: 15,  title: 'pop30_2034', subtopic_id: 5,  alias: "Projected Population for Ages 20-34 in 2030"                                                              },
     { id: 16,  title: 'pop90_3564', subtopic_id: 2,  alias: "Population for Ages 35-64 in 1990"                                                                        },
     { id: 17,  title: 'pop00_3564', subtopic_id: 2,  alias: "Population for Ages 35-64 in 2000"                                                                        },
     { id: 18,  title: 'pop10_3564', subtopic_id: 2,  alias: "Population for Ages 35-64 in 2010"                                                                        },
     { id: 19,  title: 'pop20_3564', subtopic_id: 5,  alias: "Projected Population for Ages 35-64 in 2020"                                                              },
     { id: 20,  title: 'pop30_3564', subtopic_id: 5,  alias: "Projected Population for Ages 35-64 in 2030"                                                              },
     { id: 21,  title: 'pop90_65p',  subtopic_id: 2,  alias: "Population for Ages 65 and over in 1990"                                                                  },
     { id: 22,  title: 'pop00_65p',  subtopic_id: 2,  alias: "Population for Ages 65 and over in 2000"                                                                  },
     { id: 23,  title: 'pop10_65p',  subtopic_id: 2,  alias: "Population for Ages 65 and over in 2010"                                                                  },
     { id: 24,  title: 'pop20_65p',  subtopic_id: 5,  alias: "Projected Population for Ages 65 and over in 2020"                                                        },
     { id: 25,  title: 'pop30_65p',  subtopic_id: 5,  alias: "Projected Population for Ages 65 and over in 2030"                                                        },
     { id: 26,  title: 'mage',       subtopic_id: 2,  alias: "Median Age"                                                                                               },
     { id: 27,  title: 'mageme',     subtopic_id: 2,  alias: "Median Age, Margin of Error"                                                                              },
     { id: 28,  title: 'nhwhi',      subtopic_id: 3,  alias: "Non-Hispanic White Population in 2010"                                                                    },
     { id: 29,  title: 'nhaa',       subtopic_id: 3,  alias: "Non-Hispanic Black/African American Population in 2010"                                                   },
     { id: 30,  title: 'nhas',       subtopic_id: 3,  alias: "Non-Hispanic Asian Population in 2010"                                                                    },
     { id: 31,  title: 'nhpi',       subtopic_id: 3,  alias: "Non-Hispanic Pacific Islander Population in 2010"                                                         },
     { id: 32,  title: 'nhna',       subtopic_id: 3,  alias: "Non-Hispanic Native American Population in 2010"                                                          },
     { id: 33,  title: 'lat',        subtopic_id: 3,  alias: "Hispanic/Latino Population in 2010"                                                                       },
     { id: 34,  title: 'nhmult',     subtopic_id: 3,  alias: "Non-Hispanic multi-race Population in 2010"                                                               },
     { id: 35,  title: 'nhoth',      subtopic_id: 3,  alias: "Non-Hispanic Other One Race Population in 2011"                                                           },
     { id: 36,  title: 'nhwhi_p',    subtopic_id: 3,  alias: "% Non-Hispanic White Population in 2010"                                                                  },
     { id: 37,  title: 'nhaa_p',     subtopic_id: 3,  alias: "% Non-Hispanic Black/African American Population in 2010"                                                 },
     { id: 38,  title: 'nhas_p',     subtopic_id: 3,  alias: "% Non-Hispanic Asian Population in 2010"                                                                  },
     { id: 39,  title: 'nhpi_p',     subtopic_id: 3,  alias: "% Non-Hispanic Pacific Islander Population in 2010"                                                       },
     { id: 40,  title: 'nhna_p',     subtopic_id: 3,  alias: "% Non-Hispanic Native American Population in 2010"                                                        },
     { id: 41,  title: 'lat_p',      subtopic_id: 3,  alias: "% Hispanic/Latino Population in 2010"                                                                     },
     { id: 42,  title: 'nhmult_p',   subtopic_id: 3,  alias: "% Non-Hispanic multi-race Population in 2010"                                                             },
     { id: 43,  title: 'nhoth_p',    subtopic_id: 3,  alias: "% Non-Hispanic Other One Race Population in 2010"                                                         },
     { id: 44,  title: 'whi_00',     subtopic_id: 3,  alias: "White Population in 2000"                                                                                 },
     { id: 45,  title: 'whi_00_p',   subtopic_id: 3,  alias: "% White Population in 2000"                                                                               },
     { id: 46,  title: 'minor_00',   subtopic_id: 3,  alias: "Minority Population in 2000"                                                                              },
     { id: 47,  title: 'minor_00_p', subtopic_id: 3,  alias: "% Minority Population in 2000"                                                                            },
     { id: 48,  title: 'minor_10',   subtopic_id: 3,  alias: "Minority Population in 2010"                                                                              },
     { id: 49,  title: 'minor_10_p', subtopic_id: 3,  alias: "% Minority Population in 2010"                                                                            },
     { id: 50,  title: 'enrolled',   subtopic_id: 2,  alias: "Number of Students Enrolled in 2012"                                                                              },
     { id: 51,  title: 'li_num',     subtopic_id: 2,  alias: "Low Income Students"                                                                                      },
     { id: 52,  title: 'enroll_chg', subtopic_id: 2,  alias: "Change in Enrollment since 2005-06"                                                                       },
     { id: 53,  title: 'li_chg',     subtopic_id: 2,  alias: "Change in Low Income Students since 2005-06"                                                              },
     { id: 54,  title: 'hhf_c',      subtopic_id: 6,  alias: "Family households with children in 2010"                                                                  },
     { id: 55,  title: 'hhf_c_p',    subtopic_id: 6,  alias: "% Family households with children in 2010"                                                                },
     { id: 56,  title: 'hhnf',       subtopic_id: 6,  alias: "Non-Family households with children in 2010"                                                              },
     { id: 57,  title: 'hhnf_p',     subtopic_id: 6,  alias: "% Non-Family households with children in 2010"                                                            },
     { id: 58,  title: 'hh1',        subtopic_id: 6,  alias: "Households with householder living alone in 2010"                                                         },
     { id: 59,  title: 'hh1_p',      subtopic_id: 6,  alias: "% Households with householder living alone in 2010"                                                       },
     { id: 60,  title: 'hh1_65o',    subtopic_id: 6,  alias: "Households with householder 65 years and over living alone in 2010"                                       },
     { id: 61,  title: 'hh1_65o_p',  subtopic_id: 6,  alias: "Households with householder 65 years and over living alone in 2010"                                       },
     { id: 62,  title: 'hu_oo_10',   subtopic_id: 7,  alias: "Owner-Occupied Households in 2010"                                                                        },
     { id: 63,  title: 'hu_oo_10_p', subtopic_id: 7,  alias: "% Owner-Occupied Households in 2010"                                                                      },
     { id: 64,  title: 'hu_ro_10',   subtopic_id: 7,  alias: "Renter-Occupied Households in 2010"                                                                       },
     { id: 65,  title: 'hu_ro_10_p', subtopic_id: 7,  alias: "% Renter-Occupied Households in 2010"                                                                     },
     { id: 66,  title: 'hh_00',      subtopic_id: 8,  alias: "Households in 2000"                                                                                       },
     { id: 67,  title: 'hh_10',      subtopic_id: 8,  alias: "Households in 2010"                                                                                       },
     { id: 68,  title: 'hh_20sr',    subtopic_id: 10, alias: "Projected Households in 2020"                                                                             },
     { id: 69,  title: 'hh_30sr',    subtopic_id: 10, alias: "Projected Households in 2030"                                                                             },
     { id: 70,  title: 'hh_avg00',   subtopic_id: 8,  alias: "Average Household Size in 2000"                                                                           },
     { id: 71,  title: 'hh_avg10',   subtopic_id: 8,  alias: "Average Household Size in 2010"                                                                           },
     { id: 72,  title: 'hhs_20sr',   subtopic_id: 10, alias: "Projected Average Household Size in 2020"                                                                 },
     { id: 73,  title: 'hhs_30sr',   subtopic_id: 10, alias: "Projected Average Household Size in 2030"                                                                 },
     { id: 74,  title: 'hh10_1529',  subtopic_id: 9,  alias: "Households with Householder Age 15-29 in 2010"                                                            },
     { id: 75,  title: 'hh10_3044',  subtopic_id: 9,  alias: "Households with Householder Age 30-44 in 2010"                                                            },
     { id: 76,  title: 'hh10_4559',  subtopic_id: 9,  alias: "Households with Householder Age 45-59 in 2010"                                                            },
     { id: 77,  title: 'hh10_6074',  subtopic_id: 9,  alias: "Households with Householder Age 60-74 in 2010"                                                            },
     { id: 78,  title: 'hh10_75pl',  subtopic_id: 9,  alias: "Households with Householder Age 75 and over in 2010"                                                      },
     { id: 79,  title: 'hh20_1529',  subtopic_id: 11, alias: "Projected Households with Householder Age 15-29 in 2020"                                                  },
     { id: 80,  title: 'hh20_3044',  subtopic_id: 11, alias: "Projected Households with Householder Age 30-44 in 2020"                                                  },
     { id: 81,  title: 'hh20_4559',  subtopic_id: 11, alias: "Projected Households with Householder Age 45-59 in 2020"                                                  },
     { id: 82,  title: 'hh20_6074',  subtopic_id: 11, alias: "Projected Households with Householder Age 60-74 in 2020"                                                  },
     { id: 83,  title: 'hh20_75pl',  subtopic_id: 11, alias: "Projected Households with Householder Age 75 and over in 2020"                                            },
     { id: 84,  title: 'hh30_1529',  subtopic_id: 11, alias: "Projected Households with Householder Age 15-29 in 2030"                                                  },
     { id: 85,  title: 'hh30_3044',  subtopic_id: 11, alias: "Projected Households with Householder Age 30-44 in 2030"                                                  },
     { id: 86,  title: 'hh30_4559',  subtopic_id: 11, alias: "Projected Households with Householder Age 45-59 in 2030"                                                  },
     { id: 87,  title: 'hh30_6074',  subtopic_id: 11, alias: "Projected Households with Householder Age 60-74 in 2030"                                                  },
     { id: 88,  title: 'hh30_75pl',  subtopic_id: 11, alias: "Projected Households with Householder Age 75 and over in 2030"                                            },
     { id: 89,  title: 'hu1534_20',  subtopic_id: 11, alias: "Projected Household Demand for Ages 15-34 between 2010-2020"                                              },
     { id: 90,  title: 'sfr1534_20', subtopic_id: 12, alias: "Projected Rented Single Family Household Demand for Ages 15-34 between 2010-2020"                         },
     { id: 91,  title: 'sfo1534_20', subtopic_id: 12, alias: "Projected Owned Single Family Household Demand for Ages 15-34 between 2010-2020"                          },
     { id: 92,  title: 'mfr1534_20', subtopic_id: 12, alias: "Projected Rented Multi-Family Household Demand for Ages 15-34 between 2010-2020"                          },
     { id: 93,  title: 'mfo1534_20', subtopic_id: 12, alias: "Projected Owned Multi-Family Household Demand for Ages 15-34 between 2010-2020"                           },
     { id: 94,  title: 'hu3554_20',  subtopic_id: 12, alias: "Projected Household Demand for Ages 35-54 between 2010-2020"                                              },
     { id: 95,  title: 'sfr3554_20', subtopic_id: 12, alias: "Projected Rented Single Family Household Demand for Ages 35-54 between 2010-2020"                         },
     { id: 96,  title: 'sfo3554_20', subtopic_id: 12, alias: "Projected Owned Single Family Household Demand for Ages 35-54 between 2010-2020"                          },
     { id: 97,  title: 'mfr3554_20', subtopic_id: 12, alias: "Projected Rented Multi-Family Household Demand for Ages 35-54 between 2010-2020"                          },
     { id: 98,  title: 'mfo3554_20', subtopic_id: 12, alias: "Projected Owned Multi-Family Household Demand for Ages 35-54 between 2010-2020"                           },
     { id: 99,  title: 'hu5574_20',  subtopic_id: 12, alias: "Projected Household Demand for Ages 55-74 between 2010-2020"                                              },
     { id: 100, title: 'sfr5574_20', subtopic_id: 12, alias: "Projected Rented Single Family Household Demand for Ages 55-74 between 2010-2020"                         },
     { id: 101, title: 'sfo5574_20', subtopic_id: 12, alias: "Projected Owned Single Family Household Demand for Ages 55-74 between 2010-2020"                          },
     { id: 102, title: 'mfr5574_20', subtopic_id: 12, alias: "Projected Rented Multi-Family Household Demand for Ages 55-74 between 2010-2020"                          },
     { id: 103, title: 'mfo5574_20', subtopic_id: 12, alias: "Projected Owned Multi-Family Household Demand for Ages 55-74 between 2010-2020"                           },
     { id: 104, title: 'hu75p_20',   subtopic_id: 12, alias: "Projected Household Demand for Ages 75 and over between 2010-2020"                                        },
     { id: 105, title: 'sfr75p_20',  subtopic_id: 12, alias: "Projected Rented Single Family Household Demand for Ages 75 and over between 2010-2020"                   },
     { id: 106, title: 'sfo75p_20',  subtopic_id: 12, alias: "Projected Owned Single Family Household Demand for Ages 75 and over between 2010-2020"                    },
     { id: 107, title: 'mfr75p_20',  subtopic_id: 12, alias: "Projected Rented Multi-Family Household Demand for Ages 75 and over between 2010-2020"                    },
     { id: 108, title: 'mfo75p_20',  subtopic_id: 12, alias: "Projected Owned Multi-Family Household Demand for Ages 75 and over between 2010-2020"                     },
     { id: 109, title: 'hu',         subtopic_id: 13, alias: "Estimate Housing Units"                                                                                   },
     { id: 110, title: 'hu_me',      subtopic_id: 13, alias: "Estimate Housing Units, Margin of Error"                                                                  },
     { id: 111, title: 'u1_p',       subtopic_id: 13, alias: "% Single housing units"                                                                                   },
     { id: 112, title: 'u1_mep',     subtopic_id: 13, alias: "% Single housing units, margin of error"                                                                  },
     { id: 113, title: 'u2_4_p',     subtopic_id: 13, alias: "% 2-4 housing units"                                                                                      },
     { id: 114, title: 'u2_4_mep',   subtopic_id: 13, alias: "% 2-4 housing units, margin of error"                                                                     },
     { id: 115, title: 'u5_9_p',     subtopic_id: 13, alias: "% 5-9 housing units"                                                                                      },
     { id: 116, title: 'u5_9_mep',   subtopic_id: 13, alias: "% 5-9 housing units, margin of error"                                                                     },
     { id: 117, title: 'u10_19_p',   subtopic_id: 13, alias: "% 10-19 housing units"                                                                                    },
     { id: 118, title: 'u10_19_mep', subtopic_id: 13, alias: "% 10-19 housing units, margin of error"                                                                   },
     { id: 119, title: 'u20ov_p',    subtopic_id: 13, alias: "% 20+ housing units"                                                                                      },
     { id: 120, title: 'u20ov_mep',  subtopic_id: 13, alias: "% 20+ housing units, margin of error"                                                                     },
     { id: 121, title: 'u_oth_p',    subtopic_id: 13, alias: "% Other housing units"                                                                                    },
     { id: 122, title: 'u_oth_mep',  subtopic_id: 13, alias: "% Other housing units, margin of error"                                                                   },
     { id: 123, title: 'occ_hu',     subtopic_id: 13, alias: "Estimated occupied housing units"                                                                         },
     { id: 124, title: 'occ_hu_me',  subtopic_id: 13, alias: "Estimated occupied housing units, margin of error"                                                        },
     { id: 125, title: 'h_39_p',     subtopic_id: 14, alias: "Housing units built before 1939"                                                                          },
     { id: 126, title: 'h_39_mep',   subtopic_id: 14, alias: "Housing units built before 1939, margin of error"                                                         },
     { id: 127, title: 'h4059_p',    subtopic_id: 14, alias: "Housing units built before 1940-1959"                                                                     },
     { id: 128, title: 'h4059_mep',  subtopic_id: 14, alias: "Housing units built before 1940-1959, margin of error"                                                    },
     { id: 129, title: 'h6079_p',    subtopic_id: 14, alias: "Housing units built before 1960-1979"                                                                     },
     { id: 130, title: 'h6079_mep',  subtopic_id: 14, alias: "Housing units built before 1960-1979, margin of error"                                                    },
     { id: 131, title: 'h8099_p',    subtopic_id: 14, alias: "Housing units built before 1980-2000"                                                                     },
     { id: 132, title: 'h8099_mep',  subtopic_id: 14, alias: "Housing units built before 1980-2000, margin of error"                                                    },
     { id: 133, title: 'h_00_p',     subtopic_id: 14, alias: "Housing units built in 2000 or after"                                                                     },
     { id: 134, title: 'h_00_mep',   subtopic_id: 14, alias: "Housing units built in 2000 or after, margin of error"                                                    },
     { id: 135, title: 'totunits00', subtopic_id: 15, alias: "Number of building permits in 2000"                                                                       },
     { id: 136, title: 'sf_units00', subtopic_id: 15, alias: "Single Family unit permits in 2000"                                                                       },
     { id: 137, title: 'mf_units00', subtopic_id: 15, alias: "Multi-Family unit permits in 2000"                                                                        },
     { id: 138, title: 'totunits01', subtopic_id: 15, alias: "Number of building permits in 2001"                                                                       },
     { id: 139, title: 'sf_units01', subtopic_id: 15, alias: "Single Family unit permits in 2001"                                                                       },
     { id: 140, title: 'mf_units01', subtopic_id: 15, alias: "Multi-Family unit permits in 2001"                                                                        },
     { id: 141, title: 'totunits02', subtopic_id: 15, alias: "Number of building permits in 2002"                                                                       },
     { id: 142, title: 'sf_units02', subtopic_id: 15, alias: "Single Family unit permits in 2002"                                                                       },
     { id: 143, title: 'mf_units02', subtopic_id: 15, alias: "Multi-Family unit permits in 2002"                                                                        },
     { id: 144, title: 'totunits03', subtopic_id: 15, alias: "Number of building permits in 2003"                                                                       },
     { id: 145, title: 'sf_units03', subtopic_id: 15, alias: "Single Family unit permits in 2003"                                                                       },
     { id: 146, title: 'mf_units03', subtopic_id: 15, alias: "Multi-Family unit permits in 2003"                                                                        },
     { id: 147, title: 'totunits04', subtopic_id: 15, alias: "Number of building permits in 2004"                                                                       },
     { id: 148, title: 'sf_units04', subtopic_id: 15, alias: "Single Family unit permits in 2004"                                                                       },
     { id: 149, title: 'mf_units04', subtopic_id: 15, alias: "Multi-Family unit permits in 2004"                                                                        },
     { id: 150, title: 'totunits05', subtopic_id: 15, alias: "Number of building permits in 2005"                                                                       },
     { id: 151, title: 'sf_units05', subtopic_id: 15, alias: "Single Family unit permits in 2005"                                                                       },
     { id: 152, title: 'mf_units05', subtopic_id: 15, alias: "Multi-Family unit permits in 2005"                                                                        },
     { id: 153, title: 'totunits06', subtopic_id: 15, alias: "Number of building permits in 2006"                                                                       },
     { id: 154, title: 'sf_units06', subtopic_id: 15, alias: "Single Family unit permits in 2006"                                                                       },
     { id: 155, title: 'mf_units06', subtopic_id: 15, alias: "Multi-Family unit permits in 2006"                                                                        },
     { id: 156, title: 'totunits07', subtopic_id: 15, alias: "Number of building permits in 2007"                                                                       },
     { id: 157, title: 'sf_units07', subtopic_id: 15, alias: "Single Family unit permits in 2007"                                                                       },
     { id: 158, title: 'mf_units07', subtopic_id: 15, alias: "Multi-Family unit permits in 2007"                                                                        },
     { id: 159, title: 'totunits08', subtopic_id: 15, alias: "Number of building permits in 2008"                                                                       },
     { id: 160, title: 'sf_units08', subtopic_id: 15, alias: "Single Family unit permits in 2008"                                                                       },
     { id: 161, title: 'mf_units08', subtopic_id: 15, alias: "Multi-Family unit permits in 2008"                                                                        },
     { id: 162, title: 'totunits09', subtopic_id: 15, alias: "Number of building permits in 2009"                                                                       },
     { id: 163, title: 'sf_units09', subtopic_id: 15, alias: "Single Family unit permits in 2009"                                                                       },
     { id: 164, title: 'mf_units09', subtopic_id: 15, alias: "Multi-Family unit permits in 2009"                                                                        },
     { id: 165, title: 'totunits10', subtopic_id: 15, alias: "Number of building permits in 2010"                                                                       },
     { id: 166, title: 'sf_units10', subtopic_id: 15, alias: "Single Family unit permits in 2010"                                                                       },
     { id: 167, title: 'mf_units10', subtopic_id: 15, alias: "Multi-Family unit permits in 2010"                                                                        },
     { id: 168, title: 'totunits11', subtopic_id: 15, alias: "Number of building permits in 2011"                                                                       },
     { id: 169, title: 'sf_units11', subtopic_id: 15, alias: "Single Family unit permits in 2011"                                                                       },
     { id: 170, title: 'mf_units11', subtopic_id: 15, alias: "Multi-Family unit permits in 2011"                                                                        },
     { id: 171, title: 'totunits12', subtopic_id: 15, alias: "Number of building permits in 2012"                                                                       },
     { id: 172, title: 'sf_units12', subtopic_id: 15, alias: "Single Family unit permits in 2012"                                                                       },
     { id: 173, title: 'mf_units12', subtopic_id: 15, alias: "Multi-Family unit permits in 2012"                                                                        },
     { id: 174, title: 'hhami',      subtopic_id: 13, alias: "Estimated housing units"                                                                                  },
     { id: 175, title: 'hhami_me',   subtopic_id: 13, alias: "Estimated housing units, margin of error"                                                                 },
     { id: 176, title: 'amiu30p',    subtopic_id: 16, alias: "% Households with income < 30% AMI"                                                                       },
     { id: 177, title: 'amiu30mp',   subtopic_id: 16, alias: "% Households with income < 30% AMI, margin of error"                                                      },
     { id: 178, title: 'ami3050p',   subtopic_id: 16, alias: "% Households with income 30 - 50% AMI"                                                                    },
     { id: 179, title: 'ami3050mp',  subtopic_id: 16, alias: "% Households with income 30 - 50% AMI, margin of error"                                                   },
     { id: 180, title: 'ami5080p',   subtopic_id: 16, alias: "% Households with income 50 - 80% AMI"                                                                    },
     { id: 181, title: 'ami5080mp',  subtopic_id: 16, alias: "% Households with income 50 - 80% AMI, margin of error"                                                   },
     { id: 182, title: 'ami80100p',  subtopic_id: 16, alias: "% Households with income 80 - 100% AMI"                                                                   },
     { id: 183, title: 'ami80100mp', subtopic_id: 16, alias: "% Households with income 80 - 100% AMI, margin of error"                                                  },
     { id: 184, title: 'amio100p',   subtopic_id: 16, alias: "% Households with income > 100% AMI"                                                                      },
     { id: 185, title: 'amio100mp',  subtopic_id: 16, alias: "% Households with income > 100% AMI, margin of error"                                                     },
     { id: 186, title: 'il_30_1',    subtopic_id: 17, alias: "Extremely Low (30%) Income Limits for a 1 Person Household"                                               },
     { id: 187, title: 'il_30_2',    subtopic_id: 17, alias: "Extremely Low (30%) Income Limits for a 2 Person Household"                                               },
     { id: 188, title: 'il_30_3',    subtopic_id: 17, alias: "Extremely Low (30%) Income Limits for a 3 Person Household"                                               },
     { id: 189, title: 'il_30_4',    subtopic_id: 17, alias: "Extremely Low (30%) Income Limits for a 4 Person Household"                                               },
     { id: 190, title: 'il_30_5',    subtopic_id: 17, alias: "Extremely Low (30%) Income Limits for a 5 Person Household"                                               },
     { id: 191, title: 'il_30_6',    subtopic_id: 17, alias: "Extremely Low (30%) Income Limits for a 6 Person Household"                                               },
     { id: 192, title: 'il_30_7',    subtopic_id: 17, alias: "Extremely Low (30%) Income Limits for a 7 Person Household"                                               },
     { id: 193, title: 'il_30_8',    subtopic_id: 17, alias: "Extremely Low (30%) Income Limits for a 8 Person Household"                                               },
     { id: 194, title: 'il_50_1',    subtopic_id: 17, alias: "Very Low (50%) Income Limits for a 1 Person Household"                                                    },
     { id: 195, title: 'il_50_2',    subtopic_id: 17, alias: "Very Low (50%) Income Limits for a 2 Person Household"                                                    },
     { id: 196, title: 'il_50_3',    subtopic_id: 17, alias: "Very Low (50%) Income Limits for a 3 Person Household"                                                    },
     { id: 197, title: 'il_50_4',    subtopic_id: 17, alias: "Very Low (50%) Income Limits for a 4 Person Household"                                                    },
     { id: 198, title: 'il_50_5',    subtopic_id: 17, alias: "Very Low (50%) Income Limits for a 5 Person Household"                                                    },
     { id: 199, title: 'il_50_6',    subtopic_id: 17, alias: "Very Low (50%) Income Limits for a 6 Person Household"                                                    },
     { id: 200, title: 'il_50_7',    subtopic_id: 17, alias: "Very Low (50%) Income Limits for a 7 Person Household"                                                    },
     { id: 201, title: 'il_50_8',    subtopic_id: 17, alias: "Very Low (50%) Income Limits for a 8 Person Household"                                                    },
     { id: 202, title: 'il_80_1',    subtopic_id: 17, alias: "Low (80%) Income Limits for a 1 Person Household"                                                         },
     { id: 203, title: 'il_80_2',    subtopic_id: 17, alias: "Low (80%) Income Limits for a 2 Person Household"                                                         },
     { id: 204, title: 'il_80_3',    subtopic_id: 17, alias: "Low (80%) Income Limits for a 3 Person Household"                                                         },
     { id: 205, title: 'il_80_4',    subtopic_id: 17, alias: "Low (80%) Income Limits for a 4 Person Household"                                                         },
     { id: 206, title: 'il_80_5',    subtopic_id: 17, alias: "Low (80%) Income Limits for a 5 Person Household"                                                         },
     { id: 207, title: 'il_80_6',    subtopic_id: 17, alias: "Low (80%) Income Limits for a 6 Person Household"                                                         },
     { id: 208, title: 'il_80_7',    subtopic_id: 17, alias: "Low (80%) Income Limits for a 7 Person Household"                                                         },
     { id: 209, title: 'il_80_8',    subtopic_id: 17, alias: "Low (80%) Income Limits for a 8 Person Household"                                                         },
     { id: 210, title: 'shi',        subtopic_id: 20, alias: "Number of subsidized housing Units"                                                                       },
     { id: 211, title: 'shi_p',      subtopic_id: 20, alias: "% of Total Units that are subsidized housing"                                                             },
     { id: 212, title: 'ownoccv2',   subtopic_id: 18, alias: "Owner occupied households where cost burden can be determined"                                            },
     { id: 213, title: 'ownoccv2me', subtopic_id: 18, alias: "Owner occupied households where cost burden can be determined, margin of error"                           },
     { id: 214, title: 'o_cb',       subtopic_id: 18, alias: "Owner occupied households that are cost burdened"                                                         },
     { id: 215, title: 'o_cb_me',    subtopic_id: 18, alias: "Owner occupied households that are cost burdened, margin of error"                                        },
     { id: 216, title: 'o_cb50',     subtopic_id: 18, alias: "Owner occupied households that are severely cost burdened"                                                },
     { id: 217, title: 'o_cb50me',   subtopic_id: 18, alias: "Owner occupied households that are severely cost burdened, margin of error"                               },
     { id: 218, title: 'o_cb_p',     subtopic_id: 18, alias: "% Owner occupied households that are cost burdened"                                                       },
     { id: 219, title: 'o_cb_mep',   subtopic_id: 18, alias: "% Owner occupied households that are cost burdened, margin of error"                                      },
     { id: 220, title: 'o_cb50_p',   subtopic_id: 18, alias: "% Owner occupied households that are severely cost burdened"                                              },
     { id: 221, title: 'o_cb50_mep', subtopic_id: 18, alias: "% Owner occupied households that are severely cost burdened, margin of error"                             },
     { id: 222, title: 'r_occv2',    subtopic_id: 18, alias: "Renter occupied households where cost burden can be determined"                                           },
     { id: 223, title: 'r_occv2_me', subtopic_id: 18, alias: "Renter occupied households where cost burden can be determined, margin of error"                          },
     { id: 224, title: 'r_cb',       subtopic_id: 18, alias: "Renter occupied households that are cost burdened"                                                        },
     { id: 225, title: 'r_cb_me',    subtopic_id: 18, alias: "Renter occupied households that are cost burdened, margin of error"                                       },
     { id: 226, title: 'r_cb50',     subtopic_id: 18, alias: "Renter occupied households that are severely cost burdened"                                               },
     { id: 227, title: 'r_cb50me',   subtopic_id: 18, alias: "Renter occupied households that are severely cost burdened, margin of error"                              },
     { id: 228, title: 'r_cb_p',     subtopic_id: 18, alias: "% Renter occupied households that are cost burdened"                                                      },
     { id: 229, title: 'r_cb_mep',   subtopic_id: 18, alias: "% Renter occupied households that are cost burdened, margin of error"                                     },
     { id: 230, title: 'r_cb50_p',   subtopic_id: 18, alias: "% Renter occupied households that are severely cost burdened"                                             },
     { id: 231, title: 'r_cb50_mep', subtopic_id: 18, alias: "% Renter occupied households that are severely cost burdened, margin of error"                            },
     { id: 232, title: 'eli_cbp',    subtopic_id: 16, alias: "% Households with income < 30% of AMI that are cost burdened"                                             },
     { id: 233, title: 'eli_cbmp',   subtopic_id: 16, alias: "% Households with income < 30% of AMI that are cost burdened, margin of error"                            },
     { id: 234, title: 'vli_cbp',    subtopic_id: 16, alias: "% Households with income 30 - 50% AMI that are cost burdened"                                      },
     { id: 235, title: 'vli_cbmp',   subtopic_id: 16, alias: "% Households with income 30 - 50% AMI that are cost burdened, margin of error"                     },
     { id: 236, title: 'li_cbp',     subtopic_id: 16, alias: "% Households with income 50 - 80% AMI that are cost burdened"                                             },
     { id: 237, title: 'li_cbmp',    subtopic_id: 16, alias: "% Households with income 50 - 80% AMI that are cost burdened, margin of error"                            },
     { id: 238, title: 'mod_cbp',    subtopic_id: 16, alias: "% Households with income 80 - 100% of AMI that are cost burdened"                                         },
     { id: 239, title: 'mod_cbmp',   subtopic_id: 16, alias: "% Households with income 80 - 100% of AMI that are cost burdened, margin of error"                        },
     { id: 240, title: 'hi_cbp',     subtopic_id: 16, alias: "% Households with income >100% of AMI that are cost burdened"                                             },
     { id: 241, title: 'hi_cbmp',    subtopic_id: 16, alias: "% Households with income >100% of AMI that are cost burdened, margin of error"                            },
     { id: 242, title: 'ef_cbp',     subtopic_id: 19, alias: "% Elderly Family households that are cost burdened"                                                       },
     { id: 243, title: 'ef_cbmp',    subtopic_id: 19, alias: "% Elderly Family households that are cost burdened, margin of error"                                      },
     { id: 244, title: 'sf_cbp',     subtopic_id: 19, alias: "% Small Family households that are cost burdened"                                                         },
     { id: 245, title: 'sf_cbmp',    subtopic_id: 19, alias: "% Small Family households that are cost burdened, margin of error"                                        },
     { id: 246, title: 'lf_cbp',     subtopic_id: 19, alias: "% Large Family households that are cost burdened"                                                         },
     { id: 247, title: 'lf_cbmp',    subtopic_id: 19, alias: "% Large Family households that are cost burdened, margin of error"                                        },
     { id: 248, title: 'enf_cbp',    subtopic_id: 19, alias: "% Elderly Non-Family households that are cost burdened"                                                   },
     { id: 249, title: 'enf_cbmp',   subtopic_id: 19, alias: "% Elderly Non-Family households that are cost burdened, margin of error"                                  },
     { id: 250, title: 'oth_cbp',    subtopic_id: 19, alias: "% Other householdss that are cost burdened"                                                               },
     { id: 251, title: 'oth_cbmp',   subtopic_id: 19, alias: "% Other householdss that are cost burdened, margin of error"                                              },
     { id: 252, title: 'hhinc10k',   subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $10,000."  },
     { id: 253, title: 'hhinc20k',   subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $20,000."  },
     { id: 254, title: 'hhinc30k',   subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $30,000."  },
     { id: 255, title: 'hhinc40k',   subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $40,000."  },
     { id: 256, title: 'hhinc50k',   subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $50,000."  },
     { id: 257, title: 'hhinc60k',   subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $60,000."  },
     { id: 258, title: 'hhinc70k',   subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $70,000."  },
     { id: 259, title: 'hhinc80k',   subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $80,000."  },
     { id: 260, title: 'hhinc90k',   subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $90,000."  },
     { id: 261, title: 'hhinc100k',  subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $100,000." },
     { id: 262, title: 'hhinc120k',  subtopic_id: 21, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $120,000." },
     { id: 263, title: 'affgapvli',  subtopic_id: 22, alias: "Affordability Gap in Households with income < 30% of AMI"                                                 },
     { id: 264, title: 'affgapvlim', subtopic_id: 22, alias: "Affordability Gap in Households with income < 30% of AMI, margin of error"                                },
     { id: 265, title: 'affgapli',   subtopic_id: 22, alias: "Affordability Gap in Households with income 50-80% AMI"                                                   },
     { id: 266, title: 'affgaplim',  subtopic_id: 22, alias: "Affordability Gap in Households with income 50-80% AMI, margin of error"                                  },
     { id: 267, title: 'affgapmod',  subtopic_id: 22, alias: "Affordability Gap in Households with income > 80% of AMI"                                                 },
     { id: 268, title: 'affgapmodm', subtopic_id: 22, alias: "Affordability Gap in Households with income > 80% of AMI, margin of error"                                }]
  end

  module_function :topic_areas
  module_function :topics
  module_function :subtopics
  module_function :fields
end


def print_and_flush(str)
  print str
  $stdout.flush
end



model_names = %w( TopicArea Topic Subtopic Field )

model_names.each do |model_name|
  print_and_flush "seeding #{model_name}"

  model   = Module.const_get model_name
  records = Seeds.send "#{model.table_name}"

  records.each do |record|
    rec = model.create_or_update(record, without_protection: true)
  end

  puts " -- DONE!"
end
