# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

module Seeds
  def topic_areas
   [{id: 1, title: 'Demographics'},
    {id: 2, title: 'Supply'},
    {id: 3, title: 'Affordability'}]
  end

  def topics
   [{id: 1, title: 'Population',  topic_area_id: 1},
    {id: 2, title: 'Households',  topic_area_id: 1},
    {id: 3, title: 'Projections', topic_area_id: 1},
    {id: 4, title: 'Stock',       topic_area_id: 2},
    {id: 5, title: 'Tenure',      topic_area_id: 2},
    {id: 6, title: 'Cost Burden', topic_area_id: 3},
    {id: 7, title: 'SHI',         topic_area_id: 3}]
  end

  def subtopics
   [{id: 1,  title: 'Age',                   topic_id: 2},
    {id: 2,  title: 'Type',                  topic_id: 2},
    {id: 3,  title: 'Size',                  topic_id: 2},
    {id: 4,  title: 'Age',                   topic_id: 4},
    {id: 5,  title: 'Type',                  topic_id: 4},
    {id: 6,  title: 'Tenure',                topic_id: 6},
    {id: 7,  title: 'Household Composition', topic_id: 6},
    {id: 8,  title: 'Income',                topic_id: 6},
    {id: 9,  title: 'Subsidized',            topic_id: 7},
    {id: 10, title: 'Expiring Use',          topic_id: 7}]
  end

  def fields
    [{ id: 1,   title: 'muni_id',    subtopic_id: 1,  alias: "Municipal ID"                                                                                             },
     { id: 2,   title: 'municipal',  subtopic_id: 1,  alias: "Municipality"                                                                                             },
     { id: 3,   title: 'pop_1990',   subtopic_id: 1,  alias: "Total Population, 1990"                                                                                   },
     { id: 4,   title: 'pop_2000',   subtopic_id: 1,  alias: "Total Population, 2000"                                                                                   },
     { id: 5,   title: 'pop_2010',   subtopic_id: 1,  alias: "Total Population, 2010"                                                                                   },
     { id: 6,   title: 'pop_20sr',   subtopic_id: 1,  alias: "Total Population, 2020"                                                                                   },
     { id: 7,   title: 'pop_30sr',   subtopic_id: 1,  alias: "Total Population, 2030"                                                                                   },
     { id: 8,   title: 'pop90_5_19', subtopic_id: 1,  alias: "Population Ages 5-19, 1990"                                                                               },
     { id: 9,   title: 'pop00_5_19', subtopic_id: 1,  alias: "Population Ages 5-19, 2000"                                                                               },
     { id: 10,  title: 'pop10_5_19', subtopic_id: 1,  alias: "Population Ages 5-19, 2010"                                                                               },
     { id: 11,  title: 'pop20_5_19', subtopic_id: 1,  alias: "Population Ages 5-19, 2020"                                                                               },
     { id: 12,  title: 'pop30_5_19', subtopic_id: 1,  alias: "Population Ages 5-19, 2030"                                                                               },
     { id: 13,  title: 'pop90_2034', subtopic_id: 1,  alias: "Population Ages 20-34, 1990"                                                                              },
     { id: 14,  title: 'pop00_2034', subtopic_id: 1,  alias: "Population Ages 20-34, 2000"                                                                              },
     { id: 15,  title: 'pop10_2034', subtopic_id: 1,  alias: "Population Ages 20-34, 2010"                                                                              },
     { id: 16,  title: 'pop20_2034', subtopic_id: 1,  alias: "Population Ages 20-34, 2020"                                                                              },
     { id: 17,  title: 'pop30_2034', subtopic_id: 1,  alias: "Population Ages 20-34, 2030"                                                                              },
     { id: 18,  title: 'pop90_3564', subtopic_id: 1,  alias: "Population Ages 35-64, 1990"                                                                              },
     { id: 19,  title: 'pop00_3564', subtopic_id: 1,  alias: "Population Ages 35-64, 2000"                                                                              },
     { id: 20,  title: 'pop10_3564', subtopic_id: 1,  alias: "Population Ages 35-64, 2010"                                                                              },
     { id: 21,  title: 'pop20_3564', subtopic_id: 1,  alias: "Population Ages 35-64, 2020"                                                                              },
     { id: 22,  title: 'pop30_3564', subtopic_id: 1,  alias: "Population Ages 35-64, 2030"                                                                              },
     { id: 23,  title: 'pop90_65p',  subtopic_id: 1,  alias: "Population Ages 65+, 1990"                                                                                },
     { id: 24,  title: 'pop00_65p',  subtopic_id: 1,  alias: "Population Ages 65+, 2000"                                                                                },
     { id: 25,  title: 'pop10_65p',  subtopic_id: 1,  alias: "Population Ages 65+, 2010"                                                                                },
     { id: 26,  title: 'pop20_65p',  subtopic_id: 1,  alias: "Population Ages 65+, 2020"                                                                                },
     { id: 27,  title: 'pop30_65p',  subtopic_id: 1,  alias: "Population Ages 65+, 2030"                                                                                },
     { id: 28,  title: 'mage',       subtopic_id: 1,  alias: "Median Age"                                                                                               },
     { id: 29,  title: 'mageme',     subtopic_id: 1,  alias: "Median Age, Margin of Error"                                                                              },
     { id: 30,  title: 'nhwhi',      subtopic_id: 1,  alias: "Non-Hispanic White, 2010"                                                                                 },
     { id: 31,  title: 'nhaa',       subtopic_id: 1,  alias: "Non-Hispanic Black or African American, 2010"                                                             },
     { id: 32,  title: 'nhas',       subtopic_id: 2,  alias: "Non-Hispanic Asian, 2010"                                                                                 },
     { id: 33,  title: 'nhpi',       subtopic_id: 2,  alias: "Non-Hispanic Pacific Islander, 2010"                                                                      },
     { id: 34,  title: 'nhna',       subtopic_id: 2,  alias: "Non-Hispanic Native American, 2010"                                                                       },
     { id: 35,  title: 'lat',        subtopic_id: 2,  alias: "Hispanic/Latino, 2010"                                                                                    },
     { id: 36,  title: 'nhmult',     subtopic_id: 2,  alias: "Non-Hispanic Multi-Race, 2010"                                                                            },
     { id: 37,  title: 'nhoth',      subtopic_id: 2,  alias: "Non-Hispanic Other Race, 2010"                                                                            },
     { id: 38,  title: 'nhwhi_p',    subtopic_id: 2,  alias: "% Non-Hispanic White, 2010"                                                                               },
     { id: 39,  title: 'nhaa_p',     subtopic_id: 2,  alias: "% Non-Hispanic Black or African American, 2010"                                                           },
     { id: 40,  title: 'nhas_p',     subtopic_id: 2,  alias: "% Non-Hispanic Asian, 2010"                                                                               },
     { id: 41,  title: 'nhpi_p',     subtopic_id: 2,  alias: "% Non-Hispanic Pacific Islander, 2010"                                                                    },
     { id: 42,  title: 'nhna_p',     subtopic_id: 2,  alias: "% Non-Hispanic Native American, 2010"                                                                     },
     { id: 43,  title: 'lat_p',      subtopic_id: 2,  alias: "% Hispanic/Latino, 2010"                                                                                  },
     { id: 44,  title: 'nhmult_p',   subtopic_id: 2,  alias: "% Non-Hispanic Multi-Race, 2010"                                                                          },
     { id: 45,  title: 'nhoth_p',    subtopic_id: 2,  alias: "% Non-Hispanic Other Race, 2010"                                                                          },
     { id: 46,  title: 'enrolled',   subtopic_id: 2,  alias: "Total Enrollment"                                                                                         },
     { id: 47,  title: 'schoolyear', subtopic_id: 2,  alias: "Current school year"                                                                                      },
     { id: 48,  title: 'li_num',     subtopic_id: 2,  alias: "Low Income Students"                                                                                      },
     { id: 49,  title: 'enroll_chg', subtopic_id: 2,  alias: "Change in Enrollment since 2005-06"                                                                       },
     { id: 50,  title: 'li_chg',     subtopic_id: 2,  alias: "Change in Low Income Students since 2005-06"                                                              },
     { id: 51,  title: 'hhf_c',      subtopic_id: 2,  alias: "Family Households: with own children under 18 years"                                                      },
     { id: 52,  title: 'hhf_c_p',    subtopic_id: 2,  alias: "% Family Households: with own children under 18 years"                                                    },
     { id: 53,  title: 'hhnf',       subtopic_id: 2,  alias: "Non-family Households"                                                                                    },
     { id: 54,  title: 'hhnf_p',     subtopic_id: 2,  alias: "% Non-family Households"                                                                                  },
     { id: 55,  title: 'hh1',        subtopic_id: 3,  alias: "Households with 1 person"                                                                                 },
     { id: 56,  title: 'hh1_p',      subtopic_id: 3,  alias: "% Households with 1 person"                                                                               },
     { id: 57,  title: 'hh1_65o',    subtopic_id: 3,  alias: "Households with 1 person 65 years or over"                                                                },
     { id: 58,  title: 'hh1_65o_p',  subtopic_id: 3,  alias: "% Households with 1 person 65 years or over"                                                              },
     { id: 59,  title: 'hu_oo_10',   subtopic_id: 3,  alias: "Owner Occupied Households"                                                                                },
     { id: 60,  title: 'hu_oo_10_p', subtopic_id: 3,  alias: "% Owner Occupied Households"                                                                              },
     { id: 61,  title: 'hu_ro_10',   subtopic_id: 3,  alias: "Renter Occupied Households"                                                                               },
     { id: 62,  title: 'hu_ro_10_p', subtopic_id: 3,  alias: "% Renter Occupied Households"                                                                             },
     { id: 63,  title: 'hh_00',      subtopic_id: 3,  alias: "Total Households, 2000"                                                                                   },
     { id: 64,  title: 'hh_10',      subtopic_id: 3,  alias: "Total Households, 2010"                                                                                   },
     { id: 65,  title: 'hh_20sr',    subtopic_id: 3,  alias: "Total Households, 2020"                                                                                   },
     { id: 66,  title: 'hh_30sr',    subtopic_id: 3,  alias: "Total Households, 2030"                                                                                   },
     { id: 67,  title: 'hh_avg00',   subtopic_id: 3,  alias: "Average Household Size, 2000"                                                                             },
     { id: 68,  title: 'hh_avg10',   subtopic_id: 3,  alias: "Average Household Size, 2010"                                                                             },
     { id: 69,  title: 'hhs_20sr',   subtopic_id: 3,  alias: "Average Household Size, 2020"                                                                             },
     { id: 70,  title: 'hhs_30sr',   subtopic_id: 4,  alias: "Average Household Size, 2030"                                                                             },
     { id: 71,  title: 'hh10_1529',  subtopic_id: 4,  alias: "Households with Householder Ages: 15-29, 2010"                                                            },
     { id: 72,  title: 'hh10_3044',  subtopic_id: 4,  alias: "Households with Householder Ages: 30-44, 2010"                                                            },
     { id: 73,  title: 'hh10_4559',  subtopic_id: 4,  alias: "Households with Householder Ages: 45-59, 2010"                                                            },
     { id: 74,  title: 'hh10_6074',  subtopic_id: 4,  alias: "Households with Householder Ages: 60-74, 2010"                                                            },
     { id: 75,  title: 'hh10_75pl',  subtopic_id: 4,  alias: "Households with Householder Ages: 75+, 2010"                                                              },
     { id: 76,  title: 'hh20_1529',  subtopic_id: 4,  alias: "Households with Householder Ages: 15-29, 2020"                                                            },
     { id: 77,  title: 'hh20_3044',  subtopic_id: 4,  alias: "Households with Householder Ages: 30-44, 2020"                                                            },
     { id: 78,  title: 'hh20_4559',  subtopic_id: 4,  alias: "Households with Householder Ages: 45-59, 2020"                                                            },
     { id: 79,  title: 'hh20_6074',  subtopic_id: 4,  alias: "Households with Householder Ages: 60-74, 2020"                                                            },
     { id: 80,  title: 'hh20_75pl',  subtopic_id: 4,  alias: "Households with Householder Ages: 75+, 2020"                                                              },
     { id: 81,  title: 'hh30_1529',  subtopic_id: 4,  alias: "Households with Householder Ages: 15-29, 2030"                                                            },
     { id: 82,  title: 'hh30_3044',  subtopic_id: 4,  alias: "Households with Householder Ages: 30-44, 2030"                                                            },
     { id: 83,  title: 'hh30_4559',  subtopic_id: 4,  alias: "Households with Householder Ages: 45-59, 2030"                                                            },
     { id: 84,  title: 'hh30_6074',  subtopic_id: 4,  alias: "Households with Householder Ages: 60-74, 2030"                                                            },
     { id: 85,  title: 'hh30_75pl',  subtopic_id: 4,  alias: "Households with Householder Ages: 75+, 2030"                                                              },
     { id: 86,  title: 'eli_hh10',   subtopic_id: 4,  alias: "Households with income < 30% of AMI, 2010"                                                                },
     { id: 87,  title: 'vli_hh10',   subtopic_id: 4,  alias: "Households with income 30 < 50% of AMI, 2010"                                                             },
     { id: 88,  title: 'li_hh10',    subtopic_id: 4,  alias: "Households with income 50 < 80% of AMI, 2010"                                                             },
     { id: 89,  title: 'mi_hh10',    subtopic_id: 4,  alias: "Households with income => 80% of AMI, 2010"                                                               },
     { id: 90,  title: 'eli_hh20',   subtopic_id: 4,  alias: "Households with income < 30% of AMI, 2020"                                                                },
     { id: 91,  title: 'vli_hh20',   subtopic_id: 4,  alias: "Households with income 30 < 50% of AMI, 2020"                                                             },
     { id: 92,  title: 'li_hh20',    subtopic_id: 4,  alias: "Households with income 50 < 80% of AMI, 2020"                                                             },
     { id: 93,  title: 'mi_hh20',    subtopic_id: 4,  alias: "Households with income => 80% of AMI, 2020"                                                               },
     { id: 94,  title: 'eli_hh30',   subtopic_id: 4,  alias: "Households with income < 30% of AMI, 2030"                                                                },
     { id: 95,  title: 'vli_hh30',   subtopic_id: 4,  alias: "Households with income 30 < 50% of AMI, 2030"                                                             },
     { id: 96,  title: 'li_hh30',    subtopic_id: 4,  alias: "Households with income 50 < 80% of AMI, 2030"                                                             },
     { id: 97,  title: 'mi_hh30',    subtopic_id: 4,  alias: "Households with income => 80% of AMI, 2030"                                                               },
     { id: 98,  title: 'hu1534_20',  subtopic_id: 4,  alias: "Housing Unit Demand for Ages 15-34 between 2010 and 2020 "                                                },
     { id: 99,  title: 'sfr1534_20', subtopic_id: 4,  alias: "Rented Single Family Housing Unit Demand for Ages 15-34 between 2010 and 2020 "                           },
     { id: 100, title: 'sfo1534_20', subtopic_id: 4,  alias: "Owned Single Family Housing Unit Demand for Ages 15-34 between 2010 and 2020"                             },
     { id: 101, title: 'mfr1534_20', subtopic_id: 4,  alias: "Rented Multi-Family Housing Unit Demand for Ages 15-34 between 2010 and 2020 "                            },
     { id: 102, title: 'mfo1534_20', subtopic_id: 4,  alias: "Owned Multi-Family Housing Unit Demand for Ages 15-34 between 2010 and 2020"                              },
     { id: 103, title: 'hu3554_20',  subtopic_id: 4,  alias: "Housing Unit Demand for Ages 35-54 between 2010 and 2020 "                                                },
     { id: 104, title: 'sfr3554_20', subtopic_id: 4,  alias: "Rented Single Family Housing Unit Demand for Ages 35-54 between 2010 and 2020 "                           },
     { id: 105, title: 'sfo3554_20', subtopic_id: 4,  alias: "Owned Single Family Housing Unit Demand for Ages 35-54 between 2010 and 2020"                             },
     { id: 106, title: 'mfr3554_20', subtopic_id: 4,  alias: "Rented Multi-Family Housing Unit Demand for Ages 35-54 between 2010 and 2020 "                            },
     { id: 107, title: 'mfo3554_20', subtopic_id: 4,  alias: "Owned Multi-Family Housing Unit Demand for Ages 35-54 between 2010 and 2020"                              },
     { id: 108, title: 'hu5574_20',  subtopic_id: 4,  alias: "Housing Unit Demand for Ages 55-74 between 2010 and 2020 "                                                },
     { id: 109, title: 'sfr5574_20', subtopic_id: 4,  alias: "Rented Single Family Housing Unit Demand for Ages 55-74 between 2010 and 2020 "                           },
     { id: 110, title: 'sfo5574_20', subtopic_id: 4,  alias: "Owned Single Family Housing Unit Demand for Ages 55-74 between 2010 and 2020"                             },
     { id: 111, title: 'mfr5574_20', subtopic_id: 4,  alias: "Rented Multi-Family Housing Unit Demand for Ages 55-74 between 2010 and 2020 "                            },
     { id: 112, title: 'mfo5574_20', subtopic_id: 4,  alias: "Owned Multi-Family Housing Unit Demand for Ages 55-74 between 2010 and 2020"                              },
     { id: 113, title: 'hu75p_20',   subtopic_id: 4,  alias: "Housing Unit Demand for Ages 75 and over between 2010 and 2020 "                                          },
     { id: 114, title: 'sfr75p_20',  subtopic_id: 5,  alias: "Rented Single Family Housing Unit Demand for Ages 75 and over between 2010 and 2020 "                     },
     { id: 115, title: 'sfo75p_20',  subtopic_id: 5,  alias: "Owned Single Family Housing Unit Demand for Ages 75 and over between 2010 and 2020"                       },
     { id: 116, title: 'mfr75p_20',  subtopic_id: 5,  alias: "Rented Multi-Family Housing Unit Demand for Ages 75 and over between 2010 and 2020 "                      },
     { id: 117, title: 'mfo75p_20',  subtopic_id: 5,  alias: "Owned Multi-Family Housing Unit Demand for Ages 75 and over between 2010 and 2020"                        },
     { id: 118, title: 'hu',         subtopic_id: 5,  alias: "Estimated housing units"                                                                                  },
     { id: 119, title: 'hu_me',      subtopic_id: 5,  alias: "Estimated housing units, margin of error"                                                                 },
     { id: 120, title: 'u1_p',       subtopic_id: 5,  alias: "% Single housing units"                                                                                   },
     { id: 121, title: 'u1_mep',     subtopic_id: 5,  alias: "% Single housing units, margin of error"                                                                  },
     { id: 122, title: 'u2_4_p',     subtopic_id: 5,  alias: "% 2-4 housing units"                                                                                      },
     { id: 123, title: 'u2_4_mep',   subtopic_id: 5,  alias: "% 2-4 housing units, margin of error"                                                                     },
     { id: 124, title: 'u5_9_p',     subtopic_id: 5,  alias: "% 5-9 housing units"                                                                                      },
     { id: 125, title: 'u5_9_mep',   subtopic_id: 5,  alias: "% 5-9 housing units, margin of error"                                                                     },
     { id: 126, title: 'u10_19_p',   subtopic_id: 5,  alias: "% 10-19 housing units"                                                                                    },
     { id: 127, title: 'u10_19_mep', subtopic_id: 5,  alias: "% 10-19 housing units, margin of error"                                                                   },
     { id: 128, title: 'u20ov_p',    subtopic_id: 5,  alias: "% 20+ housing units"                                                                                      },
     { id: 129, title: 'u20ov_mep',  subtopic_id: 5,  alias: "% 20+ housing units, margin of error"                                                                     },
     { id: 130, title: 'u_oth_p',    subtopic_id: 5,  alias: "% other housing units"                                                                                    },
     { id: 131, title: 'u_oth_mep',  subtopic_id: 5,  alias: "% other housing units, margin of error"                                                                   },
     { id: 132, title: 'occ_hu',     subtopic_id: 5,  alias: "Estimated occupied housing units"                                                                         },
     { id: 133, title: 'occ_hu_me',  subtopic_id: 5,  alias: "Estimated occupied housing units, margin of error"                                                        },
     { id: 134, title: 'h_39_p',     subtopic_id: 5,  alias: "Housing units built before 1939"                                                                          },
     { id: 135, title: 'h_39_mep',   subtopic_id: 5,  alias: "Housing units built before 1939, margin of error"                                                         },
     { id: 136, title: 'h4059_p',    subtopic_id: 5,  alias: "Housing units built before 1940-1959"                                                                     },
     { id: 137, title: 'h4059_mep',  subtopic_id: 5,  alias: "Housing units built before 1940-1959, margin of error"                                                    },
     { id: 138, title: 'h6079_p',    subtopic_id: 5,  alias: "Housing units built before 1960-1979"                                                                     },
     { id: 139, title: 'h6079_mep',  subtopic_id: 5,  alias: "Housing units built before 1960-1979, margin of error"                                                    },
     { id: 140, title: 'h8099_p',    subtopic_id: 5,  alias: "Housing units built before 1980-2000"                                                                     },
     { id: 141, title: 'h8099_mep',  subtopic_id: 5,  alias: "Housing units built before 1980-2000, margin of error"                                                    },
     { id: 142, title: 'h_00_p',     subtopic_id: 5,  alias: "Housing units built in 2000 or after"                                                                     },
     { id: 143, title: 'h_00_mep',   subtopic_id: 5,  alias: "Housing units built in 2000 or after, margin of error"                                                    },
     { id: 144, title: 'tot_units',  subtopic_id: 5,  alias: "Number of building permits, 2012"                                                                         },
     { id: 145, title: 'sf_units',   subtopic_id: 5,  alias: "Single Family unit permits, 2012"                                                                         },
     { id: 146, title: 'mf_units',   subtopic_id: 5,  alias: "Multi-Family unit permits, 2012"                                                                          },
     { id: 147, title: 'mf2_units',  subtopic_id: 5,  alias: "Two Family unit permits, 2012"                                                                            },
     { id: 148, title: 'mf3_4units', subtopic_id: 5,  alias: "3 - 4 Units unit permits, 2012"                                                                           },
     { id: 149, title: 'mf5ovunits', subtopic_id: 5,  alias: "5 + Units unit permits, 2012"                                                                             },
     { id: 150, title: 'hhami',      subtopic_id: 5,  alias: "Estimated housing units"                                                                                  },
     { id: 151, title: 'hhami_me',   subtopic_id: 5,  alias: "Estimated housing units, margin of error"                                                                 },
     { id: 152, title: 'amiu30p',    subtopic_id: 5,  alias: "% Households with income < 30% AMI"                                                                       },
     { id: 153, title: 'amiu30mp',   subtopic_id: 5,  alias: "% Households with income < 30% AMI, margin of error"                                                      },
     { id: 154, title: 'ami3050p',   subtopic_id: 5,  alias: "% Households with income 30 - 50% AMI"                                                                    },
     { id: 155, title: 'ami3050mp',  subtopic_id: 5,  alias: "% Households with income 30 - 50% AMI, margin of error"                                                   },
     { id: 156, title: 'ami5080p',   subtopic_id: 6,  alias: "% Households with income 50 - 80% AMI"                                                                    },
     { id: 157, title: 'ami5080mp',  subtopic_id: 6,  alias: "% Households with income 50 - 80% AMI, margin of error"                                                   },
     { id: 158, title: 'ami80100p',  subtopic_id: 6,  alias: "% Households with income 80 - 100% AMI"                                                                   },
     { id: 159, title: 'ami80100mp', subtopic_id: 6,  alias: "% Households with income 80 - 100% AMI, margin of error"                                                  },
     { id: 160, title: 'amio100p',   subtopic_id: 6,  alias: "% Households with income > 100% AMI"                                                                      },
     { id: 161, title: 'amio100mp',  subtopic_id: 6,  alias: "% Households with income > 100% AMI, margin of error"                                                     },
     { id: 162, title: 'il_30_1',    subtopic_id: 6,  alias: "Extremely Low (30%) Income Limits for a 1 Person Household"                                               },
     { id: 163, title: 'il_30_2',    subtopic_id: 6,  alias: "Extremely Low (30%) Income Limits for a 2 Person Household"                                               },
     { id: 164, title: 'il_30_3',    subtopic_id: 6,  alias: "Extremely Low (30%) Income Limits for a 3 Person Household"                                               },
     { id: 165, title: 'il_30_4',    subtopic_id: 6,  alias: "Extremely Low (30%) Income Limits for a 4 Person Household"                                               },
     { id: 166, title: 'il_30_5',    subtopic_id: 6,  alias: "Extremely Low (30%) Income Limits for a 5 Person Household"                                               },
     { id: 167, title: 'il_30_6',    subtopic_id: 6,  alias: "Extremely Low (30%) Income Limits for a 6 Person Household"                                               },
     { id: 168, title: 'il_30_7',    subtopic_id: 6,  alias: "Extremely Low (30%) Income Limits for a 7 Person Household"                                               },
     { id: 169, title: 'il_30_8',    subtopic_id: 6,  alias: "Extremely Low (30%) Income Limits for a 8 Person Household"                                               },
     { id: 170, title: 'il_50_1',    subtopic_id: 6,  alias: "Very Low (50%) Income Limits for a 1 Person Household"                                                    },
     { id: 171, title: 'il_50_2',    subtopic_id: 6,  alias: "Very Low (50%) Income Limits for a 2 Person Household"                                                    },
     { id: 172, title: 'il_50_3',    subtopic_id: 6,  alias: "Very Low (50%) Income Limits for a 3 Person Household"                                                    },
     { id: 173, title: 'il_50_4',    subtopic_id: 6,  alias: "Very Low (50%) Income Limits for a 4 Person Household"                                                    },
     { id: 174, title: 'il_50_5',    subtopic_id: 7,  alias: "Very Low (50%) Income Limits for a 5 Person Household"                                                    },
     { id: 175, title: 'il_50_6',    subtopic_id: 7,  alias: "Very Low (50%) Income Limits for a 6 Person Household"                                                    },
     { id: 176, title: 'il_50_7',    subtopic_id: 7,  alias: "Very Low (50%) Income Limits for a 7 Person Household"                                                    },
     { id: 177, title: 'il_50_8',    subtopic_id: 7,  alias: "Very Low (50%) Income Limits for a 8 Person Household"                                                    },
     { id: 178, title: 'il_80_1',    subtopic_id: 7,  alias: "Low (80%) Income Limits for a 1 Person Household"                                                         },
     { id: 179, title: 'il_80_2',    subtopic_id: 7,  alias: "Low (80%) Income Limits for a 2 Person Household"                                                         },
     { id: 180, title: 'il_80_3',    subtopic_id: 7,  alias: "Low (80%) Income Limits for a 3 Person Household"                                                         },
     { id: 181, title: 'il_80_4',    subtopic_id: 7,  alias: "Low (80%) Income Limits for a 4 Person Household"                                                         },
     { id: 182, title: 'il_80_5',    subtopic_id: 7,  alias: "Low (80%) Income Limits for a 5 Person Household"                                                         },
     { id: 183, title: 'il_80_6',    subtopic_id: 7,  alias: "Low (80%) Income Limits for a 6 Person Household"                                                         },
     { id: 184, title: 'il_80_7',    subtopic_id: 7,  alias: "Low (80%) Income Limits for a 7 Person Household"                                                         },
     { id: 185, title: 'il_80_8',    subtopic_id: 7,  alias: "Low (80%) Income Limits for a 8 Person Household"                                                         },
     { id: 186, title: 'shi',        subtopic_id: 7,  alias: "Number of subsidized housing Units"                                                                       },
     { id: 187, title: 'shi_p',      subtopic_id: 8,  alias: "% of Total Units that are subsidized housing"                                                             },
     { id: 188, title: 'ownoccv2',   subtopic_id: 8,  alias: "Owner occupied households where cost burden can be determined"                                            },
     { id: 189, title: 'ownoccv2me', subtopic_id: 8,  alias: "Owner occupied households where cost burden can be determined, margin of error"                           },
     { id: 190, title: 'o_cb',       subtopic_id: 8,  alias: "Owner occupied households that are cost burdened"                                                         },
     { id: 191, title: 'o_cb_me',    subtopic_id: 8,  alias: "Owner occupied households that are cost burdened, margin of error"                                        },
     { id: 192, title: 'o_cb50',     subtopic_id: 8,  alias: "Owner occupied households that are severely cost burdened"                                                },
     { id: 193, title: 'o_cb50me',   subtopic_id: 8,  alias: "Owner occupied households that are severely cost burdened, margin of error"                               },
     { id: 194, title: 'o_cb_p',     subtopic_id: 8,  alias: "% Owner occupied households that are cost burdened"                                                       },
     { id: 195, title: 'o_cb_mep',   subtopic_id: 8,  alias: "% Owner occupied households that are cost burdened, margin of error"                                      },
     { id: 196, title: 'o_cb50_p',   subtopic_id: 8,  alias: "% Owner occupied households that are severely cost burdened"                                              },
     { id: 197, title: 'o_cb50_mep', subtopic_id: 8,  alias: "% Owner occupied households that are severely cost burdened, margin of error"                             },
     { id: 198, title: 'r_occv2',    subtopic_id: 8,  alias: "Renter occupied households where cost burden can be determined"                                           },
     { id: 199, title: 'r_occv2_me', subtopic_id: 8,  alias: "Renter occupied households where cost burden can be determined, margin of error"                          },
     { id: 200, title: 'r_cb',       subtopic_id: 9,  alias: "Renter occupied households that are cost burdened"                                                        },
     { id: 201, title: 'r_cb_me',    subtopic_id: 9,  alias: "Renter occupied households that are cost burdened, margin of error"                                       },
     { id: 202, title: 'r_cb50',     subtopic_id: 9,  alias: "Renter occupied households that are severely cost burdened"                                               },
     { id: 203, title: 'r_cb50me',   subtopic_id: 9,  alias: "Renter occupied households that are severely cost burdened, margin of error"                              },
     { id: 204, title: 'r_cb_p',     subtopic_id: 9,  alias: "% Renter occupied households that are cost burdened"                                                      },
     { id: 205, title: 'r_cb_mep',   subtopic_id: 9,  alias: "% Renter occupied households that are cost burdened, margin of error"                                     },
     { id: 206, title: 'r_cb50_p',   subtopic_id: 9,  alias: "% Renter occupied households that are severely cost burdened"                                             },
     { id: 207, title: 'r_cb50_mep', subtopic_id: 9,  alias: "% Renter occupied households that are severely cost burdened, margin of error"                            },
     { id: 208, title: 'eli_cbp',    subtopic_id: 9,  alias: "% Households with income < 30% of AMI that are cost burdened"                                             },
     { id: 209, title: 'eli_cbmp',   subtopic_id: 10, alias: "% Households with income < 30% of AMI that are cost burdened, margin of error"                            },
     { id: 210, title: 'vli_cbp',    subtopic_id: 10, alias: "% Households with income 30 - 50% AMI of AMI that are cost burdened"                                      },
     { id: 211, title: 'vli_cbmp',   subtopic_id: 10, alias: "% Households with income 30 - 50% AMI of AMI that are cost burdened, margin of error"                     },
     { id: 212, title: 'li_cbp',     subtopic_id: 10, alias: "% Households with income 50 - 80% AMI that are cost burdened"                                             },
     { id: 213, title: 'li_cbmp',    subtopic_id: 10, alias: "% Households with income 50 - 80% AMI that are cost burdened, margin of error"                            },
     { id: 214, title: 'mod_cbp',    subtopic_id: 10, alias: "% Households with income 80 - 100% of AMI that are cost burdened"                                         },
     { id: 215, title: 'mod_cbmp',   subtopic_id: 10, alias: "% Households with income 80 - 100% of AMI that are cost burdened, margin of error"                        },
     { id: 216, title: 'hi_cbp',     subtopic_id: 10, alias: "% Households with income >100% of AMI that are cost burdened"                                             },
     { id: 217, title: 'hi_cbmp',    subtopic_id: 10, alias: "% Households with income >100% of AMI that are cost burdened, margin of error"                            },
     { id: 218, title: 'ef_cbp',     subtopic_id: 10, alias: "% Elderly Family households that are cost burdened"                                                       },
     { id: 219, title: 'ef_cbmp',    subtopic_id: 10, alias: "% Elderly Family households that are cost burdened, margin of error"                                      },
     { id: 220, title: 'sf_cbp',     subtopic_id: 10, alias: "% Small Family households that are cost burdened"                                                         },
     { id: 221, title: 'sf_cbmp',    subtopic_id: 10, alias: "% Small Family households that are cost burdened, margin of error"                                        },
     { id: 222, title: 'lf_cbp',     subtopic_id: 10, alias: "% Large Family households that are cost burdened"                                                         },
     { id: 223, title: 'lf_cbmp',    subtopic_id: 10, alias: "% Large Family households that are cost burdened, margin of error"                                        },
     { id: 224, title: 'enf_cbp',    subtopic_id: 10, alias: "% Elderly Non-Family households that are cost burdened"                                                   },
     { id: 225, title: 'enf_cbmp',   subtopic_id: 10, alias: "% Elderly Non-Family households that are cost burdened, margin of error"                                  },
     { id: 226, title: 'oth_cbp',    subtopic_id: 10, alias: "% Other householdss that are cost burdened"                                                               },
     { id: 227, title: 'oth_cbmp',   subtopic_id: 10, alias: "% Other householdss that are cost burdened, margin of error"                                              },
     { id: 228, title: 'hhinc10k',   subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $10,000."  },
     { id: 229, title: 'hhinc20k',   subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $20,000."  },
     { id: 230, title: 'hhinc30k',   subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $30,000."  },
     { id: 231, title: 'hhinc40k',   subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $40,000."  },
     { id: 232, title: 'hhinc50k',   subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $50,000."  },
     { id: 233, title: 'hhinc60k',   subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $60,000."  },
     { id: 234, title: 'hhinc70k',   subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $70,000."  },
     { id: 235, title: 'hhinc80k',   subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $80,000."  },
     { id: 236, title: 'hhinc90k',   subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $90,000."  },
     { id: 237, title: 'hhinc100k',  subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $100,000." },
     { id: 238, title: 'hhinc120k',  subtopic_id: 10, alias: "% of single family homes sold since 2000 that were affordable to households with an incomes of $120,000." },
     { id: 239, title: 'affgapvli',  subtopic_id: 10, alias: "Affordability Gap in Households with income < 30% of AMI"                                                 },
     { id: 240, title: 'affgapvlim', subtopic_id: 10, alias: "Affordability Gap in Households with income < 30% of AMI, margin of error"                                },
     { id: 241, title: 'affgapli',   subtopic_id: 10, alias: "Affordability Gap in Households with income 50-80% AMI"                                                   },
     { id: 242, title: 'affgaplim',  subtopic_id: 10, alias: "Affordability Gap in Households with income 50-80% AMI, margin of error"                                  },
     { id: 243, title: 'affgapmod',  subtopic_id: 10, alias: "Affordability Gap in Households with income > 80% of AMI"                                                 },
     { id: 244, title: 'affgapmodm', subtopic_id: 10, alias: "Affordability Gap in Households with income > 80% of AMI, margin of error"                                }]
  end

  module_function :topic_areas
  module_function :topics
  module_function :subtopics
  module_function :fields
end


def print_and_flush(str)
  print str
  $stdout.flush
end



model_names = %w( TopicArea Topic Subtopic Field )

model_names.each do |model_name|
  print_and_flush "seeding #{model_name}"

  model   = Module.const_get model_name
  records = Seeds.send "#{model.table_name}"

  records.each do |record|
    rec = model.create_or_update(record, without_protection: true)
  end

  puts " -- DONE!"
end



